name: CI-CD pipeline

on:
  push:
    branches:
      - master

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run list all files command
        run: ls -la