name: CI/CD Pipeline
on:
  push:
    branches:
      - master

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - name: Run a command
        run: echo "Hello world"

      - name: Checkout step
        uses: actions/checkout@v4

      - name: Run command
        run: ls -ll
